### ISSUE TITLE
Not working after SSL-activation?

### ISSUE THREAD

**Issue by Digidani** [moy/piwigo-random#2]
I don´t know if it is an issue - but I changed the protocol of my phpbb3-board to https/SSL and the random pictures are gone. They were not displayed. Do I have to change something? Piwigo himself runs with http.

Thats my actual code:

`<?php // -*- mode:php c-basic-offset: 2 -*-
// +-----------------------------------------------------------------------+
// | Piwigo RANDOM - Insert images from a Piwigo Galery in a website       |
// +-----------------------------------------------------------------------+
// | Copyright(C) 2014, 2015 Matthieu Moy                                  |
// +-----------------------------------------------------------------------+
// | This program is free software; you can redistribute it and/or modify  |
// | it under the terms of the GNU General Public License as published by  |
// | the Free Software Foundation; either version 2 of the License, or     |
// | (at your option) any later version.                                   |
// |                                                                       |
// | This program is distributed in the hope that it will be useful, but   |
// | WITHOUT ANY WARRANTY; without even the implied warranty of            |
// | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      |
// | General Public License for more details.                              |
// |                                                                       |
// | You should have received a copy of the GNU General Public License     |
// | along with this program; if not, write to the Free Software           |
// | Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, |
// | USA.                                                                  |
// +-----------------------------------------------------------------------+

// Your piwigo gallery here:
$protocol = ((!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off') || $_SERVER['SERVER_PORT'] == 443 || $_SERVER['HTTP_X_FORWARDED_PORT'] == 443) ? "https://" : "http://";
$site = $protocol . "www.dhk-galerie.de/dhkfotos/";

// You should not have to modify anything below:
$maximages = 4;
$cat_id = null;
$element_name = 'several';
$mode = 'javascript';
$target = '_blank';
$size = 'thumb';

$error = '';

if (is_numeric($_GET['4']))
{
  $maximages = intval($_GET['4']);
}

if (is_numeric($_GET['null']))
{
  $cat_id = intval($_GET['null']);
}

if (isset($_GET['several']))
{
  $element_name = $_GET['several'];
}

if (isset($_GET['blank']))
{
  $target = $_GET['blank'];
}

if (isset($_GET['thumb']))
{
  $size = $_GET['thumb'];
}

if (isset($_GET['javascript'])) {
  $mode = $_GET['javascript'];
}

function check_param($param, $values) {
  global $error;
  global $$param;
  if (!in_array($$param, $values, true)) {
    if ($error != '') {
      $error .= ', ';
    }
    $error .= 'Invalid value \'' . $$param . '\' for parameter \'' . $param
      . '\' (possible values are: ' . implode(', ', $values) . ')';
  }
}

check_param('size', array('square', 'thumb', '2small', 'xsmall', 'small', 'medium', 'large', 'xlarge', 'xxlarge'));
check_param('mode', array('html', 'javascript'));

header('Content-Type: text/javascript');
if ($error != '') {
  echo 'document.getElementById('. json_encode($element_name) . ').innerHTML = ' . json_encode(
    '<strong>piwigo-random error:</strong> ' . htmlspecialchars($error) . '.') . ';';
  echo 'console.log('. json_encode('piwigo-random error:' . $error) . ');';
  exit(1);
}

$url = $site . "ws.php" .
  "?format=php" .
  "&method=pwg.categories.getImages" .
  ($cat_id ? "&cat_id=" . $cat_id : "") .
  "&recursive=true" .
  "&per_page=" . $maximages .
  "&page=1" .
  "&order=random";
$response = file_get_contents($url);
$thumbc = unserialize($response);

if ($thumbc["stat"] === 'ok')
{
  foreach ($thumbc["result"]["images"] as $image)
  {
    $image_url = (string)$image['derivatives'][$size]['url'];
    $page_url = (string)$image['page_url'];
    $comment = (string)$image['comment'];
    if ($comment === '') {
      $comment = "Zufallsbild";
    }
    $comment .= "\n(Klicken zur Ansicht in Galerie)";
    if ($mode === 'javascript') {
      // Would be a bit simpler with jquery, but let's not
      // force it for such a simple piece of code.
      ?>
      var newImg = document.createElement("img");
      newImg.src = <?php echo json_encode($image_url); ?>;
      newImg.alt = "";
      newImg.title = <?php echo json_encode($comment) ?>;
      var newLink = document.createElement("a");
      newLink.href = <?php echo json_encode($page_url); ?>;
      newLink.id = "rndpic-a";
      newLink.appendChild(newImg);
      newLink.target = <?php echo json_encode($target); ?>;
      var target = document.getElementById(<?php echo json_encode($element_name); ?>);
      if (!target)
      {
        // Could not find #random_image. As a
        // fall-back, try to find the parent of the
        // <script> tag calling us.
        // http://stackoverflow.com/questions/6932679/get-dom-element-where-script-tag-is
        var target = document.documentElement;
        while (target.childNodes.length && target.lastChild.nodeType == 1)
        {
          target = target.lastChild;
        }
        target = target.parentNode;
      }
      target.appendChild(newLink);
      <?php
    } else if ($mode === 'html') {
      echo '<a id="rndpic-a" href="' . htmlspecialchars($page_url) .
	'" target="' . htmlspecialchars($target) . '"><img src="'
        . htmlspecialchars($image_url) . '" alt="" title="' . htmlspecialchars($comment) . '" />'
        . '</a>';
    }
  }
}
else
{
  // Silent error.
  // echo "Error";
}
`

At the phpbb3 I call the plugin with these code:

`<center>
<div id="several">
<style type="text/css" scoped>
	/* Margin around each image */
	img {padding:1px; margin:1px; margin-left: 2px; margin-right: 2px;}
      </style>
      <script type="text/javascript"
	      src="//www.dresdens-harter-kern.de/phpbb3/piwigo-random-backend.php?element_name=several&amp;maximages=4"
	      async>
      </script>
    </div>
</center>`

**Comment by moy** [comment]
Hi,

FYI, I'm using piwigo-random with HTTPS on my website, it does work.

There's an issue in the code you've given, line 73 you have `''` instead of `'` several times, it results in a PHP error. I suppose this is a cut and paste error, since you don't seem to have the syntax error at https://www.dresdens-harter-kern.de/phpbb3/piwigo-random-backend.php.

OTOH, just open the page https://www.dresdens-harter-kern.de/phpbb3/piwigo-random-backend.php in your browser and see the error messages there:

<pre>
<br />
<b>Warning</b>:  file_get_contents(): Peer certificate CN=`*.kasserver.com' did not match expected CN=`www.dhk-galerie.de' in <b>/www/htdocs/w0089e06/phpbb3/piwigo-random-backend.php</b> on line <b>97</b><br />
<br />
<b>Warning</b>:  file_get_contents(): Failed to enable crypto in <b>/www/htdocs/w0089e06/phpbb3/piwigo-random-backend.php</b> on line <b>97</b><br />
<br />
<b>Warning</b>:  file_get_contents(https://www.dhk-galerie.de/dhkfotos/ws.php?format=php&amp;method=pwg.categories.getImages&amp;recursive=true&amp;per_page=4&amp;page=1&amp;order=random): failed to open stream: operation failed in <b>/www/htdocs/w0089e06/phpbb3/piwigo-random-backend.php</b> on line <b>97</b><br />
</pre>

My browser also complains rightfully about an insecure site when I open https://www.dhk-galerie.de/dhkfotos/, BTW.

Your Piwigo gallery has an HTTPS certificate for `*.kasserver.com` and you call it as `https://www.dhk-galerie.de`, hence the HTTPS verification fails.

One workaround is to use plain HTTP from piwigo-random-backend.php to your Piwigo gallery, but it considerably reduces the advantage of using HTTPS: not only attackers that control the network between your website and your piwigo gallery would be able to inject malicious code, but the piwigo server would return image URLs as HTTP URLs, hence HTTP content would be added to your HTTPS page (modern browser sometimes just refuse to display such content).

Another option would be to call your gallery (at the top of `piwigo-random-backend.php`) with the name corresponding to the HTTPS certificate (it seems to be dd35528.kasserver.com, but apparently it doesn't accept to be called by this name on HTTP).

Obviously, best would be to fix the certificate issue on your piwigo gallery.

**Comment by Digidani** [comment]
How can I do that?

> One workaround is to use plain HTTP from piwigo-random-backend.php to your Piwigo gallery

**Comment by moy** [comment]
A starting point would be to force `$protocol = 'http';` instead of the auto-detection line 24. But as I said, this will result in HTTP URLs for images. At best the browser will complain, and probably it will refuse to display the images.

The real solution is to fix the certificate on your gallery. It's 2018, HTTPS is not that hard to get right and becoming the standard more or less everywhere.

**Comment by Digidani** [comment]
I know, but I have have no idea what the problem is with the certificate. The name isn´t correct - but I create it automatically at the backend of my hoster. It´s a let´s encrypt certificate and looks good - but don´t work...  :-(

**Comment by moy** [comment]
Do you have the same provider for your gallery hosting and for the DNS name that points to it?

**Comment by Digidani** [comment]
Yes, I think so. All pages are hosted by the same provider. Other pages have also a let´s encrypt-certificate and works fine. Only piwigo don´t work.

At backend you can find this at certificate:

Gemeinsamer Name [CN] | dhk-galerie.de
Certificate for | dhk-galerie.de, www.dhk-galerie.de

**Comment by Digidani** [comment]
https://www.dhk-galerie.de/dhkfotos/ works fine. But there ist a redirect in htaccess (Redirect /index.html http://www.dhk-galerie.de/dhkfotos/) - and if I change the URL to https an error comes:  NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by Digidani** [comment]
Don´t ask me why - but now it works. Without any changes. I´m going crazy...

**Comment by moy** [comment]
Not sure whether you changed something, but I went to your gallery again and my browser doesn't complain anymore.
